// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdTf054I7l-H3g-RwQcyI5LdAOWWBRRyo',
    appId: '1:525423404443:web:d7fcda0da4871245dbad3e',
    messagingSenderId: '525423404443',
    projectId: 'ibtikar-attendance-system',
    authDomain: 'ibtikar-attendance-system.firebaseapp.com',
    databaseURL: 'https://ibtikar-attendance-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ibtikar-attendance-system.appspot.com',
    measurementId: 'G-SQEQ7KZHZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI9jOHJaHhpoE_DRXzlnXNFxYIvS2_jyk',
    appId: '1:525423404443:android:ac1df2d5d042d388dbad3e',
    messagingSenderId: '525423404443',
    projectId: 'ibtikar-attendance-system',
    databaseURL: 'https://ibtikar-attendance-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ibtikar-attendance-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHk6WoiJS1qF3ekC92hHm8wT4kv8kQ_Tg',
    appId: '1:525423404443:ios:94aa6b221a63c3eedbad3e',
    messagingSenderId: '525423404443',
    projectId: 'ibtikar-attendance-system',
    databaseURL: 'https://ibtikar-attendance-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ibtikar-attendance-system.appspot.com',
    iosBundleId: 'com.example.qrScanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHk6WoiJS1qF3ekC92hHm8wT4kv8kQ_Tg',
    appId: '1:525423404443:ios:94aa6b221a63c3eedbad3e',
    messagingSenderId: '525423404443',
    projectId: 'ibtikar-attendance-system',
    databaseURL: 'https://ibtikar-attendance-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ibtikar-attendance-system.appspot.com',
    iosBundleId: 'com.example.qrScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdTf054I7l-H3g-RwQcyI5LdAOWWBRRyo',
    appId: '1:525423404443:web:6b7bb661869a75e2dbad3e',
    messagingSenderId: '525423404443',
    projectId: 'ibtikar-attendance-system',
    authDomain: 'ibtikar-attendance-system.firebaseapp.com',
    databaseURL: 'https://ibtikar-attendance-system-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ibtikar-attendance-system.appspot.com',
    measurementId: 'G-8QQJ22D9WT',
  );
}
